// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WalletCommand — сообщение в топике wallet.commands.
// Публикуется proxy после синтаксической валидации, читается worker'ом.
type WalletCommand struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MsgUuid string                 `protobuf:"bytes,1,opt,name=msg_uuid,json=msgUuid,proto3" json:"msg_uuid,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*WalletCommand_CreateWallet
	//	*WalletCommand_Transfer
	//	*WalletCommand_GetWallet
	Body          isWalletCommand_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletCommand) Reset() {
	*x = WalletCommand{}
	mi := &file_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletCommand) ProtoMessage() {}

func (x *WalletCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletCommand.ProtoReflect.Descriptor instead.
func (*WalletCommand) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *WalletCommand) GetMsgUuid() string {
	if x != nil {
		return x.MsgUuid
	}
	return ""
}

func (x *WalletCommand) GetBody() isWalletCommand_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WalletCommand) GetCreateWallet() *CreateWalletCommand {
	if x != nil {
		if x, ok := x.Body.(*WalletCommand_CreateWallet); ok {
			return x.CreateWallet
		}
	}
	return nil
}

func (x *WalletCommand) GetTransfer() *TransferCommand {
	if x != nil {
		if x, ok := x.Body.(*WalletCommand_Transfer); ok {
			return x.Transfer
		}
	}
	return nil
}

func (x *WalletCommand) GetGetWallet() *GetWalletCommand {
	if x != nil {
		if x, ok := x.Body.(*WalletCommand_GetWallet); ok {
			return x.GetWallet
		}
	}
	return nil
}

type isWalletCommand_Body interface {
	isWalletCommand_Body()
}

type WalletCommand_CreateWallet struct {
	CreateWallet *CreateWalletCommand `protobuf:"bytes,2,opt,name=create_wallet,json=createWallet,proto3,oneof"`
}

type WalletCommand_Transfer struct {
	Transfer *TransferCommand `protobuf:"bytes,3,opt,name=transfer,proto3,oneof"`
}

type WalletCommand_GetWallet struct {
	GetWallet *GetWalletCommand `protobuf:"bytes,4,opt,name=get_wallet,json=getWallet,proto3,oneof"`
}

func (*WalletCommand_CreateWallet) isWalletCommand_Body() {}

func (*WalletCommand_Transfer) isWalletCommand_Body() {}

func (*WalletCommand_GetWallet) isWalletCommand_Body() {}

type CreateWalletCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletCommand) Reset() {
	*x = CreateWalletCommand{}
	mi := &file_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletCommand) ProtoMessage() {}

func (x *CreateWalletCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletCommand.ProtoReflect.Descriptor instead.
func (*CreateWalletCommand) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWalletCommand) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateWalletCommand) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type TransferCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromWalletId  string                 `protobuf:"bytes,1,opt,name=from_wallet_id,json=fromWalletId,proto3" json:"from_wallet_id,omitempty"`
	ToWalletId    string                 `protobuf:"bytes,2,opt,name=to_wallet_id,json=toWalletId,proto3" json:"to_wallet_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferCommand) Reset() {
	*x = TransferCommand{}
	mi := &file_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferCommand) ProtoMessage() {}

func (x *TransferCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferCommand.ProtoReflect.Descriptor instead.
func (*TransferCommand) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *TransferCommand) GetFromWalletId() string {
	if x != nil {
		return x.FromWalletId
	}
	return ""
}

func (x *TransferCommand) GetToWalletId() string {
	if x != nil {
		return x.ToWalletId
	}
	return ""
}

func (x *TransferCommand) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetWalletCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletCommand) Reset() {
	*x = GetWalletCommand{}
	mi := &file_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletCommand) ProtoMessage() {}

func (x *GetWalletCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletCommand.ProtoReflect.Descriptor instead.
func (*GetWalletCommand) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetWalletCommand) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

// WalletResult — сообщение в топике wallet.results.
// Публикуется worker'ом после обработки команды, читается напрямую
// клиентом (в 1 итерации — тем же процессом, что отправил запрос).
type WalletResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MsgUuid string                 `protobuf:"bytes,1,opt,name=msg_uuid,json=msgUuid,proto3" json:"msg_uuid,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*WalletResult_CreateWallet
	//	*WalletResult_Transfer
	//	*WalletResult_Error
	//	*WalletResult_GetWallet
	Body          isWalletResult_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResult) Reset() {
	*x = WalletResult{}
	mi := &file_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResult) ProtoMessage() {}

func (x *WalletResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResult.ProtoReflect.Descriptor instead.
func (*WalletResult) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *WalletResult) GetMsgUuid() string {
	if x != nil {
		return x.MsgUuid
	}
	return ""
}

func (x *WalletResult) GetBody() isWalletResult_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WalletResult) GetCreateWallet() *CreateWalletResult {
	if x != nil {
		if x, ok := x.Body.(*WalletResult_CreateWallet); ok {
			return x.CreateWallet
		}
	}
	return nil
}

func (x *WalletResult) GetTransfer() *TransferResult {
	if x != nil {
		if x, ok := x.Body.(*WalletResult_Transfer); ok {
			return x.Transfer
		}
	}
	return nil
}

func (x *WalletResult) GetError() *WalletResultError {
	if x != nil {
		if x, ok := x.Body.(*WalletResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *WalletResult) GetGetWallet() *GetWalletResult {
	if x != nil {
		if x, ok := x.Body.(*WalletResult_GetWallet); ok {
			return x.GetWallet
		}
	}
	return nil
}

type isWalletResult_Body interface {
	isWalletResult_Body()
}

type WalletResult_CreateWallet struct {
	CreateWallet *CreateWalletResult `protobuf:"bytes,2,opt,name=create_wallet,json=createWallet,proto3,oneof"`
}

type WalletResult_Transfer struct {
	Transfer *TransferResult `protobuf:"bytes,3,opt,name=transfer,proto3,oneof"`
}

type WalletResult_Error struct {
	Error *WalletResultError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type WalletResult_GetWallet struct {
	GetWallet *GetWalletResult `protobuf:"bytes,5,opt,name=get_wallet,json=getWallet,proto3,oneof"`
}

func (*WalletResult_CreateWallet) isWalletResult_Body() {}

func (*WalletResult_Transfer) isWalletResult_Body() {}

func (*WalletResult_Error) isWalletResult_Body() {}

func (*WalletResult_GetWallet) isWalletResult_Body() {}

type CreateWalletResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResult) Reset() {
	*x = CreateWalletResult{}
	mi := &file_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResult) ProtoMessage() {}

func (x *CreateWalletResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResult.ProtoReflect.Descriptor instead.
func (*CreateWalletResult) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *CreateWalletResult) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *CreateWalletResult) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CreateWalletResult) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type TransferResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromBalance   float64                `protobuf:"fixed64,1,opt,name=from_balance,json=fromBalance,proto3" json:"from_balance,omitempty"`
	ToBalance     float64                `protobuf:"fixed64,2,opt,name=to_balance,json=toBalance,proto3" json:"to_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResult) Reset() {
	*x = TransferResult{}
	mi := &file_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResult) ProtoMessage() {}

func (x *TransferResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResult.ProtoReflect.Descriptor instead.
func (*TransferResult) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *TransferResult) GetFromBalance() float64 {
	if x != nil {
		return x.FromBalance
	}
	return 0
}

func (x *TransferResult) GetToBalance() float64 {
	if x != nil {
		return x.ToBalance
	}
	return 0
}

type GetWalletResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResult) Reset() {
	*x = GetWalletResult{}
	mi := &file_proto_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResult) ProtoMessage() {}

func (x *GetWalletResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResult.ProtoReflect.Descriptor instead.
func (*GetWalletResult) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetWalletResult) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetWalletResult) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GetWalletResult) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetWalletResult) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type WalletResultError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResultError) Reset() {
	*x = WalletResultError{}
	mi := &file_proto_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResultError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResultError) ProtoMessage() {}

func (x *WalletResultError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResultError.ProtoReflect.Descriptor instead.
func (*WalletResultError) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{8}
}

func (x *WalletResultError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_messages_proto protoreflect.FileDescriptor

const file_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messages.proto\x12\x06wallet\"\xe8\x01\n" +
	"\rWalletCommand\x12\x19\n" +
	"\bmsg_uuid\x18\x01 \x01(\tR\amsgUuid\x12B\n" +
	"\rcreate_wallet\x18\x02 \x01(\v2\x1b.wallet.CreateWalletCommandH\x00R\fcreateWallet\x125\n" +
	"\btransfer\x18\x03 \x01(\v2\x17.wallet.TransferCommandH\x00R\btransfer\x129\n" +
	"\n" +
	"get_wallet\x18\x04 \x01(\v2\x18.wallet.GetWalletCommandH\x00R\tgetWalletB\x06\n" +
	"\x04body\"L\n" +
	"\x13CreateWalletCommand\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"q\n" +
	"\x0fTransferCommand\x12$\n" +
	"\x0efrom_wallet_id\x18\x01 \x01(\tR\ffromWalletId\x12 \n" +
	"\fto_wallet_id\x18\x02 \x01(\tR\n" +
	"toWalletId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"/\n" +
	"\x10GetWalletCommand\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"\x97\x02\n" +
	"\fWalletResult\x12\x19\n" +
	"\bmsg_uuid\x18\x01 \x01(\tR\amsgUuid\x12A\n" +
	"\rcreate_wallet\x18\x02 \x01(\v2\x1a.wallet.CreateWalletResultH\x00R\fcreateWallet\x124\n" +
	"\btransfer\x18\x03 \x01(\v2\x16.wallet.TransferResultH\x00R\btransfer\x121\n" +
	"\x05error\x18\x04 \x01(\v2\x19.wallet.WalletResultErrorH\x00R\x05error\x128\n" +
	"\n" +
	"get_wallet\x18\x05 \x01(\v2\x17.wallet.GetWalletResultH\x00R\tgetWalletB\x06\n" +
	"\x04body\"g\n" +
	"\x12CreateWalletResult\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"R\n" +
	"\x0eTransferResult\x12!\n" +
	"\ffrom_balance\x18\x01 \x01(\x01R\vfromBalance\x12\x1d\n" +
	"\n" +
	"to_balance\x18\x02 \x01(\x01R\ttoBalance\"\x7f\n" +
	"\x0fGetWalletResult\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"-\n" +
	"\x11WalletResultError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x16Z\x14wallet-service/protob\x06proto3"

var (
	file_proto_messages_proto_rawDescOnce sync.Once
	file_proto_messages_proto_rawDescData []byte
)

func file_proto_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)))
	})
	return file_proto_messages_proto_rawDescData
}

var file_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_messages_proto_goTypes = []any{
	(*WalletCommand)(nil),       // 0: wallet.WalletCommand
	(*CreateWalletCommand)(nil), // 1: wallet.CreateWalletCommand
	(*TransferCommand)(nil),     // 2: wallet.TransferCommand
	(*GetWalletCommand)(nil),    // 3: wallet.GetWalletCommand
	(*WalletResult)(nil),        // 4: wallet.WalletResult
	(*CreateWalletResult)(nil),  // 5: wallet.CreateWalletResult
	(*TransferResult)(nil),      // 6: wallet.TransferResult
	(*GetWalletResult)(nil),     // 7: wallet.GetWalletResult
	(*WalletResultError)(nil),   // 8: wallet.WalletResultError
}
var file_proto_messages_proto_depIdxs = []int32{
	1, // 0: wallet.WalletCommand.create_wallet:type_name -> wallet.CreateWalletCommand
	2, // 1: wallet.WalletCommand.transfer:type_name -> wallet.TransferCommand
	3, // 2: wallet.WalletCommand.get_wallet:type_name -> wallet.GetWalletCommand
	5, // 3: wallet.WalletResult.create_wallet:type_name -> wallet.CreateWalletResult
	6, // 4: wallet.WalletResult.transfer:type_name -> wallet.TransferResult
	8, // 5: wallet.WalletResult.error:type_name -> wallet.WalletResultError
	7, // 6: wallet.WalletResult.get_wallet:type_name -> wallet.GetWalletResult
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_messages_proto_init() }
func file_proto_messages_proto_init() {
	if File_proto_messages_proto != nil {
		return
	}
	file_proto_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*WalletCommand_CreateWallet)(nil),
		(*WalletCommand_Transfer)(nil),
		(*WalletCommand_GetWallet)(nil),
	}
	file_proto_messages_proto_msgTypes[4].OneofWrappers = []any{
		(*WalletResult_CreateWallet)(nil),
		(*WalletResult_Transfer)(nil),
		(*WalletResult_Error)(nil),
		(*WalletResult_GetWallet)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_proto_depIdxs,
		MessageInfos:      file_proto_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_proto = out.File
	file_proto_messages_proto_goTypes = nil
	file_proto_messages_proto_depIdxs = nil
}
