// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/wallet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_CreateWalletAsync_FullMethodName = "/wallet.WalletService/CreateWalletAsync"
	WalletService_GetWalletAsync_FullMethodName    = "/wallet.WalletService/GetWalletAsync"
	WalletService_TransferAsync_FullMethodName     = "/wallet.WalletService/TransferAsync"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Публичный API — только асинхронный. Каждый rpc синтаксически валидирует
// вход, публикует команду в Kafka (wallet.commands) и сразу отвечает
// AcceptedResponse. Итоговый результат приходит отдельным сообщением в
// wallet.results — клиент подписывается на топик и сопоставляет ответ по
// request_id (см. proto/messages.proto).
type WalletServiceClient interface {
	CreateWalletAsync(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletAcceptedResponse, error)
	GetWalletAsync(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletAcceptedResponse, error)
	TransferAsync(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferAcceptedResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) CreateWalletAsync(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletAcceptedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWalletAcceptedResponse)
	err := c.cc.Invoke(ctx, WalletService_CreateWalletAsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetWalletAsync(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletAcceptedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletAcceptedResponse)
	err := c.cc.Invoke(ctx, WalletService_GetWalletAsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) TransferAsync(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferAcceptedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferAcceptedResponse)
	err := c.cc.Invoke(ctx, WalletService_TransferAsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility.
//
// Публичный API — только асинхронный. Каждый rpc синтаксически валидирует
// вход, публикует команду в Kafka (wallet.commands) и сразу отвечает
// AcceptedResponse. Итоговый результат приходит отдельным сообщением в
// wallet.results — клиент подписывается на топик и сопоставляет ответ по
// request_id (см. proto/messages.proto).
type WalletServiceServer interface {
	CreateWalletAsync(context.Context, *CreateWalletRequest) (*CreateWalletAcceptedResponse, error)
	GetWalletAsync(context.Context, *GetWalletRequest) (*GetWalletAcceptedResponse, error)
	TransferAsync(context.Context, *TransferRequest) (*TransferAcceptedResponse, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) CreateWalletAsync(context.Context, *CreateWalletRequest) (*CreateWalletAcceptedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWalletAsync not implemented")
}
func (UnimplementedWalletServiceServer) GetWalletAsync(context.Context, *GetWalletRequest) (*GetWalletAcceptedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletAsync not implemented")
}
func (UnimplementedWalletServiceServer) TransferAsync(context.Context, *TransferRequest) (*TransferAcceptedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferAsync not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}
func (UnimplementedWalletServiceServer) testEmbeddedByValue()                       {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call panics, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_CreateWalletAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateWalletAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_CreateWalletAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateWalletAsync(ctx, req.(*CreateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetWalletAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWalletAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetWalletAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWalletAsync(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_TransferAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).TransferAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_TransferAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).TransferAsync(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWalletAsync",
			Handler:    _WalletService_CreateWalletAsync_Handler,
		},
		{
			MethodName: "GetWalletAsync",
			Handler:    _WalletService_GetWalletAsync_Handler,
		},
		{
			MethodName: "TransferAsync",
			Handler:    _WalletService_TransferAsync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/wallet.proto",
}
