// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/wallet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	MsgUuid       string                 `protobuf:"bytes,3,opt,name=msg_uuid,json=msgUuid,proto3" json:"msg_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_proto_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWalletRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateWalletRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateWalletRequest) GetMsgUuid() string {
	if x != nil {
		return x.MsgUuid
	}
	return ""
}

type CreateWalletAcceptedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgUuid       string                 `protobuf:"bytes,1,opt,name=msg_uuid,json=msgUuid,proto3" json:"msg_uuid,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletAcceptedResponse) Reset() {
	*x = CreateWalletAcceptedResponse{}
	mi := &file_proto_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletAcceptedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletAcceptedResponse) ProtoMessage() {}

func (x *CreateWalletAcceptedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletAcceptedResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletAcceptedResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWalletAcceptedResponse) GetMsgUuid() string {
	if x != nil {
		return x.MsgUuid
	}
	return ""
}

func (x *CreateWalletAcceptedResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	MsgUuid       string                 `protobuf:"bytes,2,opt,name=msg_uuid,json=msgUuid,proto3" json:"msg_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_proto_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *GetWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetWalletRequest) GetMsgUuid() string {
	if x != nil {
		return x.MsgUuid
	}
	return ""
}

type GetWalletAcceptedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgUuid       string                 `protobuf:"bytes,1,opt,name=msg_uuid,json=msgUuid,proto3" json:"msg_uuid,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletAcceptedResponse) Reset() {
	*x = GetWalletAcceptedResponse{}
	mi := &file_proto_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletAcceptedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletAcceptedResponse) ProtoMessage() {}

func (x *GetWalletAcceptedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletAcceptedResponse.ProtoReflect.Descriptor instead.
func (*GetWalletAcceptedResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *GetWalletAcceptedResponse) GetMsgUuid() string {
	if x != nil {
		return x.MsgUuid
	}
	return ""
}

func (x *GetWalletAcceptedResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromWalletId  string                 `protobuf:"bytes,1,opt,name=from_wallet_id,json=fromWalletId,proto3" json:"from_wallet_id,omitempty"`
	ToWalletId    string                 `protobuf:"bytes,2,opt,name=to_wallet_id,json=toWalletId,proto3" json:"to_wallet_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	MsgUuid       string                 `protobuf:"bytes,4,opt,name=msg_uuid,json=msgUuid,proto3" json:"msg_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_proto_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *TransferRequest) GetFromWalletId() string {
	if x != nil {
		return x.FromWalletId
	}
	return ""
}

func (x *TransferRequest) GetToWalletId() string {
	if x != nil {
		return x.ToWalletId
	}
	return ""
}

func (x *TransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetMsgUuid() string {
	if x != nil {
		return x.MsgUuid
	}
	return ""
}

type TransferAcceptedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgUuid       string                 `protobuf:"bytes,1,opt,name=msg_uuid,json=msgUuid,proto3" json:"msg_uuid,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferAcceptedResponse) Reset() {
	*x = TransferAcceptedResponse{}
	mi := &file_proto_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferAcceptedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferAcceptedResponse) ProtoMessage() {}

func (x *TransferAcceptedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferAcceptedResponse.ProtoReflect.Descriptor instead.
func (*TransferAcceptedResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *TransferAcceptedResponse) GetMsgUuid() string {
	if x != nil {
		return x.MsgUuid
	}
	return ""
}

func (x *TransferAcceptedResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_wallet_proto protoreflect.FileDescriptor

const file_proto_wallet_proto_rawDesc = "" +
	"\n" +
	"\x12proto/wallet.proto\x12\x06wallet\"g\n" +
	"\x13CreateWalletRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x19\n" +
	"\bmsg_uuid\x18\x03 \x01(\tR\amsgUuid\"Q\n" +
	"\x1cCreateWalletAcceptedResponse\x12\x19\n" +
	"\bmsg_uuid\x18\x01 \x01(\tR\amsgUuid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"J\n" +
	"\x10GetWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x19\n" +
	"\bmsg_uuid\x18\x02 \x01(\tR\amsgUuid\"N\n" +
	"\x19GetWalletAcceptedResponse\x12\x19\n" +
	"\bmsg_uuid\x18\x01 \x01(\tR\amsgUuid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x8c\x01\n" +
	"\x0fTransferRequest\x12$\n" +
	"\x0efrom_wallet_id\x18\x01 \x01(\tR\ffromWalletId\x12 \n" +
	"\fto_wallet_id\x18\x02 \x01(\tR\n" +
	"toWalletId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x19\n" +
	"\bmsg_uuid\x18\x04 \x01(\tR\amsgUuid\"M\n" +
	"\x18TransferAcceptedResponse\x12\x19\n" +
	"\bmsg_uuid\x18\x01 \x01(\tR\amsgUuid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x82\x02\n" +
	"\rWalletService\x12V\n" +
	"\x11CreateWalletAsync\x12\x1b.wallet.CreateWalletRequest\x1a$.wallet.CreateWalletAcceptedResponse\x12M\n" +
	"\x0eGetWalletAsync\x12\x18.wallet.GetWalletRequest\x1a!.wallet.GetWalletAcceptedResponse\x12J\n" +
	"\rTransferAsync\x12\x17.wallet.TransferRequest\x1a .wallet.TransferAcceptedResponseB\x16Z\x14wallet-service/protob\x06proto3"

var (
	file_proto_wallet_proto_rawDescOnce sync.Once
	file_proto_wallet_proto_rawDescData []byte
)

func file_proto_wallet_proto_rawDescGZIP() []byte {
	file_proto_wallet_proto_rawDescOnce.Do(func() {
		file_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wallet_proto_rawDesc), len(file_proto_wallet_proto_rawDesc)))
	})
	return file_proto_wallet_proto_rawDescData
}

var file_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_wallet_proto_goTypes = []any{
	(*CreateWalletRequest)(nil),          // 0: wallet.CreateWalletRequest
	(*CreateWalletAcceptedResponse)(nil), // 1: wallet.CreateWalletAcceptedResponse
	(*GetWalletRequest)(nil),             // 2: wallet.GetWalletRequest
	(*GetWalletAcceptedResponse)(nil),    // 3: wallet.GetWalletAcceptedResponse
	(*TransferRequest)(nil),              // 4: wallet.TransferRequest
	(*TransferAcceptedResponse)(nil),     // 5: wallet.TransferAcceptedResponse
}
var file_proto_wallet_proto_depIdxs = []int32{
	0, // 0: wallet.WalletService.CreateWalletAsync:input_type -> wallet.CreateWalletRequest
	2, // 1: wallet.WalletService.GetWalletAsync:input_type -> wallet.GetWalletRequest
	4, // 2: wallet.WalletService.TransferAsync:input_type -> wallet.TransferRequest
	1, // 3: wallet.WalletService.CreateWalletAsync:output_type -> wallet.CreateWalletAcceptedResponse
	3, // 4: wallet.WalletService.GetWalletAsync:output_type -> wallet.GetWalletAcceptedResponse
	5, // 5: wallet.WalletService.TransferAsync:output_type -> wallet.TransferAcceptedResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_wallet_proto_init() }
func file_proto_wallet_proto_init() {
	if File_proto_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wallet_proto_rawDesc), len(file_proto_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wallet_proto_goTypes,
		DependencyIndexes: file_proto_wallet_proto_depIdxs,
		MessageInfos:      file_proto_wallet_proto_msgTypes,
	}.Build()
	File_proto_wallet_proto = out.File
	file_proto_wallet_proto_goTypes = nil
	file_proto_wallet_proto_depIdxs = nil
}
